Repository lelouchB/final-space-api, pull requests merged in 2020-10, with the labels that each got.

#39 Add react axios example
  frontend/docs/react.md
  frontend/docs/react.mdx
  frontend/package.json
Labels: hacktoberfest-accepted

#69 Add prettier
  backend/.prettierignore
  backend/.prettierrc.json
  backend/README.md
  backend/config/db.js
  backend/controllers/api.js
  backend/controllers/character.api.js
  backend/models/character.model.js
  backend/package-lock.json
  backend/package.json
  backend/routes/routes.js
  backend/server.js
Labels: enhancement, hacktoberfest

#85 Add env example
  backend/.env.example
  backend/README.md
Labels: enhancement, hacktoberfest

#100 startServer()
  backend/controllers/api.js
  backend/routes/routes.js
  backend/server.js
Labels: hacktoberfest

#90 added eslint with base in project style code
  backend/.eslintrc.js
  backend/package-lock.json
  backend/package.json
Labels: backend, enhancement, hacktoberfest

#130 Added Vue Example
  frontend/docs/vue.mdx
  frontend/sidebars.js
  frontend/static/img/assets/locationCharacterVueResult.webp
  frontend/static/img/assets/locationCharacterVueResultDark.webp
  frontend/static/img/assets/locationVueResult.webp
  frontend/static/img/assets/locationVueResultDark.webp
Labels: hacktoberfest-accepted

#109 add Vanilla js and Vanilla js + axios static examples
  frontend/docs/javascript.mdx
  frontend/sidebars.js
  frontend/static/img/assets/vanillaJsResult.webp
Labels: hacktoberfest, hacktoberfest-accepted
